# This workflow will install Python dependencies, run tests with Python unittest

name: tests

on:
  push:
    branches: [ regex ]
  pull_request:
    branches: [ regex ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, linux-latest]
        python-version: ["2.x", "3.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Test 
      run: |
        python -m unittest tests/test.py
